### ISSUE TITLE
Promise-pool installs a lot of test dependencies with --no-optional --production flags

### ISSUE THREAD

**Issue by jhakonen** [mixmaxhq/promise-pool#3]
When I install promise-pool with command:
`npm install @mixmaxhq/promise-pool@"^1.1.0" --save --no-optional --production`
A lot of test utilities gets installed, which we do not need in our production environment.

As such I think the `ava` and `ava-spec` should be in `devDependencies` and not in `dependencies`.

**Comment by ttacon** [comment]
Absolutely, thanks for bringing this to our attention! `@mixmaxhq/promise-pool@1.1.1` is now released which resolves this (see #4 ).
