### ISSUE TITLE
`PromisePool should limit concurrent execution to 3` does not pass

### ISSUE THREAD

**Issue by spencer-brown** [mixmaxhq/promise-pool#5]
Flagging this before the conversion to npm since this issue was present on `master` before the conversion.

It would be nice if alongside this fix we also wired up this repo to Travis.

**Comment by skeggse** [comment]
Apparently something broke between Node 6 and Node 8 here.

**Comment by skeggse** [comment]
[This](https://gist.github.com/skeggse/11bd97a0f154205edf6d37342cd443da) behavior changed. Fixed in #7.
